/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../studio/schema.json
export type AnswerOption = {
  _type: "answerOption";
  text: string;
  isCorrect?: boolean;
};

export type Question = {
  _type: "question";
  questionText: string;
  questionType: "radio" | "text";
  media?: {
    type?: "image" | "video";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    videoSource?: "external" | "file";
    videoUrl?: string;
    videoFile?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
  };
  options?: Array<{
    _key: string;
  } & AnswerOption>;
  correctAnswer?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Quiz = {
  _id: string;
  _type: "quiz";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  wrongAnswerPenalty: number;
  questions: Array<{
    _key: string;
  } & Question>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes = AnswerOption | Question | BlockContent | Quiz | SanityImageCrop | SanityImageHotspot | Settings | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
} | null;

// Source: sanity/lib/queries.ts
// Variable: allQuizzesQuery
// Query: *[_type == "quiz"] | order(_createdAt desc) {    _id,    title,    description,    "questionCount": count(questions)  }
export type AllQuizzesQueryResult = Array<{
  _id: string;
  title: string;
  description: string | null;
  questionCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: quizByIdQuery
// Query: *[_type == "quiz" && _id == $quizId][0] {    _id,    title,    description,    wrongAnswerPenalty,    questions[] {      _key,      questionText,      questionType,      media {        type,        image {          asset->{            _id,            url,            metadata { lqip, dimensions }          },          alt        },        videoSource,        videoUrl,        videoFile {          asset->{            _id,            url          }        }      },      options[] {        _key,        text,        isCorrect      },      correctAnswer    }  }
export type QuizByIdQueryResult = {
  _id: string;
  title: string;
  description: string | null;
  wrongAnswerPenalty: number;
  questions: Array<{
    _key: string;
    questionText: string;
    questionType: "radio" | "text";
    media: {
      type: "image" | "video" | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: null;
      } | null;
      videoSource: "external" | "file" | null;
      videoUrl: string | null;
      videoFile: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
    options: Array<{
      _key: string;
      text: string;
      isCorrect: boolean | null;
    }> | null;
    correctAnswer: string | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: quizForPlayerQuery
// Query: *[_type == "quiz" && _id == $quizId][0] {    _id,    title,    description,    wrongAnswerPenalty,    "totalQuestions": count(questions),    questions[] {      _key,      questionText,      questionType,      media {        type,        image {          asset->{            _id,            url,            metadata { lqip, dimensions }          },          alt        },        videoSource,        videoUrl,        videoFile {          asset->{            _id,            url          }        }      },      options[] {        _key,        text      }    }  }
export type QuizForPlayerQueryResult = {
  _id: string;
  title: string;
  description: string | null;
  wrongAnswerPenalty: number;
  totalQuestions: number;
  questions: Array<{
    _key: string;
    questionText: string;
    questionType: "radio" | "text";
    media: {
      type: "image" | "video" | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: null;
      } | null;
      videoSource: "external" | "file" | null;
      videoUrl: string | null;
      videoFile: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
    options: Array<{
      _key: string;
      text: string;
    }> | null;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"settings\"][0]": SettingsQueryResult;
    "\n  *[_type == \"quiz\"] | order(_createdAt desc) {\n    _id,\n    title,\n    description,\n    \"questionCount\": count(questions)\n  }\n": AllQuizzesQueryResult;
    "\n  *[_type == \"quiz\" && _id == $quizId][0] {\n    _id,\n    title,\n    description,\n    wrongAnswerPenalty,\n    questions[] {\n      _key,\n      questionText,\n      questionType,\n      media {\n        type,\n        image {\n          asset->{\n            _id,\n            url,\n            metadata { lqip, dimensions }\n          },\n          alt\n        },\n        videoSource,\n        videoUrl,\n        videoFile {\n          asset->{\n            _id,\n            url\n          }\n        }\n      },\n      options[] {\n        _key,\n        text,\n        isCorrect\n      },\n      correctAnswer\n    }\n  }\n": QuizByIdQueryResult;
    "\n  *[_type == \"quiz\" && _id == $quizId][0] {\n    _id,\n    title,\n    description,\n    wrongAnswerPenalty,\n    \"totalQuestions\": count(questions),\n    questions[] {\n      _key,\n      questionText,\n      questionType,\n      media {\n        type,\n        image {\n          asset->{\n            _id,\n            url,\n            metadata { lqip, dimensions }\n          },\n          alt\n        },\n        videoSource,\n        videoUrl,\n        videoFile {\n          asset->{\n            _id,\n            url\n          }\n        }\n      },\n      options[] {\n        _key,\n        text\n      }\n    }\n  }\n": QuizForPlayerQueryResult;
  }
}

